### ISSUE TITLE
Search by title

### ISSUE THREAD

**Issue by vuphuong87** [chrisjp/IMDb-PHP-API#1]
It seems that search by title doesn't work anymore. Anyone gets this issue?

**Comment by chrisjp** [comment]
Yeah just tested it myself and I'm seeing it too. Looks like the API is requiring a signature appended to the URL again, at least for that method to work. I've fixed this already, I'd simply missed some code when porting the Ruby gem to PHP.

Unfortunately this has led to a strange issue now - for some reason it's still returning 0 results (bad sig error) if used with the anonymiser service (the other methods are all still working fine).

I think most people will want to continue anonymising their requests so I'm going to hold off pushing the code for now. In the meantime I'm going to look into this and try and figure it out what's up with it ASAP and then get the fix pushed.

**Comment by chrisjp** [comment]
I have just pushed code to fix this issue. Unfortunately, anonymising the request will still return an empty result set. The only solution to this at the moment is simply to set $anonymise to false if you need to use the find_by_title() method. All other methods seem to work fine when anoymised.

I'll look into either finding a way to fix it or finding an alternative service that works, but can't promise anything.

**Comment by vuphuong87** [comment]
thank for your works @chrisjp  :)
